FROM  continuumio/conda-ci-linux-64-python3.8

LABEL authors="eva.hamrud@crick.ac.uk" \
      description="Docker image containing conda and HOMER"

# Install homer
RUN conda install -c bioconda homer