name: docker-build-push
#https://github.com/marketplace/actions/build-and-push-docker-images

on:
  push:
    branches:
      - main
    paths: 
      - '**/Dockerfile'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 1
      matrix:
        docker-file: ["Dockerfile"]
        module-name: ["archr_dev_macs2", "archr_hicdc", "hicontacts", "conda_homer", "scenicplus", "archr_seurat_signac_mega"]

    steps:
      - uses: actions/checkout@v2
      - name: Set version and tags
        id: ver
        run: |
          VERSION=`cat containers/${{matrix.module-name}}/VERSION`
          echo "version: $VERSION"
          echo "::set-output name=version::$(echo $VERSION)"
        shell: bash
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/${{matrix.module-name}}
          path: containers/${{matrix.module-name}}
          dockerfile: containers/${{matrix.module-name}}/${{matrix.docker-file}}
          tags: latest,${{steps.ver.outputs.version}}
