name: docker-build-push-multiarch

on:
  push:
    branches:
      - main
    paths: 
      - '**/TEMP_NONE/Dockerfile'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 1
      matrix:
        docker-file: ["Dockerfile"]
        module-name: ["seurat-monocle-arm"]
        
    steps:
      - uses: actions/checkout@v2

      - name: Set version and tags
        id: ver
        run: |
          VERSION=`cat containers/${{matrix.module-name}}/VERSION`
          echo "version: $VERSION"
          echo "::set-output name=version::$(echo $VERSION)"
        shell: bash

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (push)
        run: |
          docker buildx build \
            --tag alexthiery/${{matrix.module-name}}:${{steps.ver.outputs.version}} \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            containers/${{matrix.module-name}}